import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import MarginOfBody from "@/components/MarginOfBody";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster"


const recursive= Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${recursive.className} relative bg-green-100  `}>
        <Header/>
        <MarginOfBody>
        {children}
        <Toaster/>
        </MarginOfBody>
        </body>
    </html>
  );
}
